spring:
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/reservation
    username: root
    password: 123456

  redis:
    redisson:
      config: |
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          password: null
          clientName: null
          address: "redis://127.0.0.1:6379"
          subscriptionsPerConnection: 2
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 32
          connectionMinimumIdleSize: 8
          connectionPoolSize: 32
          database: 0
          dnsMonitoringInterval: 5000
        threads: 8
        nettyThreads: 16
        codec: !<org.redisson.codec.JsonJacksonCodec> {}
        transportMode: "NIO"
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  global-config:
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath*:/mapper/**/*.xml, classpath*:/model/mapper/**/*.xml

jwt:
  key: rest
  timeout: 12

minio:
  host: http://127.0.0.1:39000
  ak: 2ftPDdhsYbfQ7Bzd
  sk: gWGN9eru1kpCuCaMEIlDoW3XLuYx1D1A
  bucket: rest-storage
  timeout: 1

pagehelper:
  auto-dialect: true
  support-methods-arguments: true